# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

export DIRENV_LOG_FORMAT=""
set -gx DIRENV_LOG_LEVEL off
set -gx DIRENV_LOG_FORMAT ""
# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/0ix2vag410y4map4k27bg12k7aqlwlmd-hm-session-vars.fish/etc/profile.d/hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "~/.local/share/fish/home-manager/generated_completions" $post
    end

    set -g fish_greeting
    fastfetch
    #    eval "$(atuin init fish)"
    if not set -q IN_NIX_SHELL
        atuin init fish | source
    end
    

    # Dracula theme colors
    set --global fish_color_autosuggestion 6272a4
    set --global fish_color_cancel 'ff5555 --reverse'
    set --global fish_color_command 8be9fd
    set --global fish_color_comment 6272a4
    set --global fish_color_cwd 50fa7b
    set --global fish_color_cwd_root red
    set --global fish_color_end ffb86c
    set --global fish_color_error ff5555
    set --global fish_color_escape ff79c6
    set --global fish_color_history_current --bold
    set --global fish_color_host bd93f9
    set --global fish_color_host_remote bd93f9
    set --global fish_color_keyword ff79c6
    set --global fish_color_match '--background=brblue'
    set --global fish_color_normal f8f8f2
    set --global fish_color_operator 50fa7b
    set --global fish_color_option ffb86c
    set --global fish_color_param bd93f9
    set --global fish_color_quote f1fa8c
    set --global fish_color_redirection f8f8f2
    set --global fish_color_search_match '--background=44475a'
    set --global fish_color_selection '--background=44475a'
    set --global fish_color_status ff5555
    set --global fish_color_user 8be9fd
    set --global fish_color_valid_path --underline
    set --global fish_pager_color_completion f8f8f2
    set --global fish_pager_color_description 6272a4
    set --global fish_pager_color_prefix 8be9fd
    set --global fish_pager_color_progress 6272a4
    set --global fish_pager_color_selected_background '--background=44475a'
    set --global fish_pager_color_selected_completion f8f8f2
    set --global fish_pager_color_selected_description 6272a4
    set --global fish_pager_color_selected_prefix 8be9fd

end
