# -----------------------------------------------------
# Environment Variables — NixOS + Wayland ready
# -----------------------------------------------------

# Wayland / XDG
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CURRENT_DESKTOP,Hyprland

# Qt Wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum

# GTK / GDK
env = GDK_BACKEND,wayland,x11
env = GDK_SCALE,1
env = GTK_USE_PORTAL,1
env = GSETTINGS_BACKEND,dcomf

# Firefox / Mozilla
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_DBUS_REMOTE,1

# Java / Electron / IntelliJ
env = IDEA_USE_X11,1
env = _JAVA_AWT_WM_NONREPARENTING,1
env = _JAVA_OPTIONS,-Dawt.useSystemAAFontSettings=on
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# Editors
env = EDITOR,nvim
env = VISUAL,nvim
env = TERMINAL,kitty

# SDL
env = SDL_VIDEODRIVER,wayland

# Clutter
env = CLUTTER_BACKEND,wayland

# NixOS: Nix path hints (ajusta al tuyo si usas flakes)
env = NIX_PROFILES,/nix/var/nix/profiles/default:$HOME/.nix-profile
env = NIXOS_OZONE_WL,1

# Theming
env = GTK_THEME,catppuccin-mocha-green-standard
env = XCURSOR_THEME,Qogir-dark
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Qogir-dark
env = HYPRCURSOR_SIZE,24
